(in-package :discompiler)

(defun pe-header-signature-pointer (bytes)
   (struct-value "e_lfanew" (msdos-header bytes)))

(defun pe-header-signature-validp (bytes)
  (let ((pointer (pe-header-signature-pointer bytes)))
    (if (array-in-bounds-p bytes pointer)
        (equalp
         (bytes bytes +long+ pointer)
         (list (char-code #\P) (char-code #\E) 0 0))
        nil)))

(defun msdos-header (bytes)
  (let ((offset 0)
        (elements  `((,(* 2 +char+) "signature")
                     (+short+ "lastsize")
                     (+short+ "nblocks")
                     (+short+ "nreloc")
                     (+short+ "hdrsize")
                     (+short+ "minalloc")
                     (+short+ "maxalloc")
                     (+short+ "*ss")
                     (+short+ "*sp")
                     (+short+ "checksum")
                     (+short+ "*ip")
                     (+short+ "*cs")
                     (+short+ "relocpos")
                     (+short+ "noverlay")
                     (,(* 4 +short+) "reserved1")
                     (+short+ "oem_id")
                     (+short+ "oem_info")
                     (,(* 10 +short+) "reserved2")
                     (+long+ "e_lfanew"))))
    (multiple-value-bind (data structure-size)
        (c-structure-values bytes elements offset)
      (values data structure-size))))
