(in-package :discompiler)

(defun optional-header-signature-pointer (bytes)
  (multiple-value-bind (d s) (coff-header bytes)
    s))

(defun optional-header-signature (bytes)
  (bytes-to-type-int
   (bytes bytes +short+ (optional-header-signature-pointer bytes))))

(defun optional-header-image-type (bytes)
  (let ((signature (optional-header-signature bytes)))
    (cond ((eq signature #x10b) 'pe32)
          ((eq signature #x20b) 'pe32+)
          (T nil))))

(defun optional-header-standard-fields (bytes)
  (let* ((offset (optional-header-signature-pointer bytes))
         (header-type (optional-header-image-type bytes))
         (long-or-double (if (eq (optional-header-image-type bytes) 'PE32)
                             '+long+
                             '+double-long+))
         (elements (append '((+short+ "Magic")
                             (+char+ "MajorLinkerVersion")
                             (+char+ "MinorLinkerVersion")
                             (+long+ "SizeOfCode")
                             (+long+ "SizeOfInitializedData")
                             (+long+ "SizeOfUninitializedData")
                             (+long+ "AddressOfEntryPoint")
                             (+long+ "BaseOfCode"))
                           (when  (eq header-type 'PE32)
                             '((+long+ "BaseOfData")))
                           `((,long-or-double "ImageBase")
                             (+long+ "SectionAlignment")
                             (+long+ "FileAlignment")
                             (+short+ "MajorOperatingSystemVersion")
                             (+short+ "MinorOperatingSystemVersion")
                             (+short+ "MajorImageVersion")
                             (+short+ "MinorImageVersion")
                             (+short+ "MajorSubsystemVersion")
                             (+short+ "MinorSubsystemVersion")
                             (+long+ "Reserved")
                             (+long+ "SizeOfImage")
                             (+long+ "SizeOfHeaders")
                             (+long+ "CheckSum")
                             (+short+ "Subsystem")
                             (+short+ "DLLCharacteristics")
                             (,long-or-double "SizeOfStackReserve")
                             (,long-or-double "SizeOfStackCommit")
                             (,long-or-double "SizeOfHeapReserve")
                             (,long-or-double "SizeOfHeapCommit")
                             (+long+ "LoaderFlags")
                             (+long+ "NumberOfRvaAndSizes")))))
    (multiple-value-bind (data structure-size)
        (c-structure-values bytes elements offset)
      (values data structure-size))))
