(in-package :discompiler)

(defun pe-header-signature-pointer (bytes)
  (bytes-to-type-int (bytes bytes +long+ 60)))

(defun pe-header-signature-validp (bytes)
  (let ((pointer (pe-header-signature-pointer bytes)))
    (if (array-in-bounds-p bytes pointer)
        (equalp
         (bytes bytes +long+ pointer)
         '(80 69 0 0))
        nil)))

(defun msdos-header (bytes)
  (let ((offset 0)
        (elements '(((* 2 +char+) "signature")
                    (+short+ "lastsize")
                    (+short+ "nblocks")
                    (+short+ "nreloc")
                    (+short+ "hdrsize")
                    (+short+ "minalloc")
                    (+short+ "maxalloc")
                    (+void+ "*ss")
                    (+void+ "*sp")
                    (+short+ "checksum")
                    (+void+ "*ip")
                    (+void+ "*cs")
                    (+short+ "relocpos")
                    (+short+ "noverlay")
                    ((* 4 +short+) "reserved1")
                    (+short+ "oem_id")
                    (+short+ "oem_info")
                    ((* 10 +short+) "reserved2")
                    (+long+ "e_lfanew"))))
    (multiple-value-bind (data structure-size)
        (c-structure-values bytes elements offset)
      (values data structure-size))))
