(in-package :discompiler)

(defun section-header (bytes offset)
  (let ((elements '((+double-long+ "Name")
                    (+long+ "VirtualSize")
                    (+long+ "VirtualAddress")
                    (+long+ "SizeOfRawData")
                    (+long+ "PointerToRawData")
                    (+long+ "PointerToRelocations")
                    (+long+ "PointerToLinenumbers")
                    (+short+ "NumberOfRelocations")
                    (+short+ "NumberOfLinenumbers")
                    (+long+ "Characteristics"))))
    (multiple-value-bind (data structure-size)
        (c-structure-values bytes elements offset)
      (values
       (cons (append (butlast (car data))
                     (list (int-to-text (car (last (car data))))))
             (cdr data))
       structure-size))))

(defun sections (bytes)
  (let ((offset)
        (optional-header-data)
        (section-data))
    (multiple-value-setq (optional-header-data offset)
      (optional-header bytes))
    (values
     (loop for x
        from 1
        to (struct-value "NumberOfSections" (coff-header bytes))
        do
          (multiple-value-setq (section-data offset)
            (section-header bytes offset))
        collect section-data)
     offset)))

(defun section-characteristics (bytes offset)
  (let ((characteristics
         (struct-value "Characteristics" (section-header bytes offset)))
        (codes '((IMAGE_SCN_TYPE_NO_PAD                #x00000008)
                 (IMAGE_SCN_CNT_CODE                   #x00000020)
                 (IMAGE_SCN_CNT_INITIALIZED_DATA       #x00000040)
                 (IMAGE_SCN_CNT_UNINITIALIZED_DATA     #x00000080)
                 (IMAGE_SCN_LNK_OTHER                  #x00000100)
                 (IMAGE_SCN_LNK_INFO                   #x00000200)
                 (IMAGE_SCN_LNK_REMOVE                 #x00000800)
                 (IMAGE_SCN_LNK_COMDAT                 #x00001000)
                 (IMAGE_SCN_NO_DEFER_SPEC_EXC          #x00004000)
                 (IMAGE_SCN_GPREL                      #x00008000)
                 (IMAGE_SCN_MEM_FARDATA                #x00008000)
                 (IMAGE_SCN_MEM_PURGEABLE              #x00020000)
                 (IMAGE_SCN_MEM_16BIT                  #x00020000)
                 (IMAGE_SCN_MEM_LOCKED                 #x00040000)
                 (IMAGE_SCN_MEM_PRELOAD                #x00080000)
                 (IMAGE_SCN_ALIGN_1BYTES               #x00100000)
                 (IMAGE_SCN_ALIGN_2BYTES               #x00200000)
                 (IMAGE_SCN_ALIGN_4BYTES               #x00300000)
                 (IMAGE_SCN_ALIGN_8BYTES               #x00400000)
                 (IMAGE_SCN_ALIGN_16BYTES              #x00500000)
                 (IMAGE_SCN_ALIGN_32BYTES              #x00600000)
                 (IMAGE_SCN_ALIGN_64BYTES              #x00700000)
                 (IMAGE_SCN_ALIGN_128BYTES             #x00800000)
                 (IMAGE_SCN_ALIGN_256BYTES             #x00900000)
                 (IMAGE_SCN_ALIGN_512BYTES             #x00A00000)
                 (IMAGE_SCN_ALIGN_1024BYTES            #x00B00000)
                 (IMAGE_SCN_ALIGN_2048BYTES            #x00C00000)
                 (IMAGE_SCN_ALIGN_4096BYTES            #x00D00000)
                 (IMAGE_SCN_ALIGN_8192BYTES            #x00E00000)
                 (IMAGE_SCN_ALIGN_MASK                 #x00F00000)
                 (IMAGE_SCN_LNK_NRELOC_OVFL            #x01000000)
                 (IMAGE_SCN_MEM_DISCARDABLE            #x02000000)
                 (IMAGE_SCN_MEM_NOT_CACHED             #x04000000)
                 (IMAGE_SCN_MEM_NOT_PAGED              #x08000000)
                 (IMAGE_SCN_MEM_SHARED                 #x10000000)
                 (IMAGE_SCN_MEM_EXECUTE                #x20000000)
                 (IMAGE_SCN_MEM_READ                   #x40000000)
                 (IMAGE_SCN_MEM_WRITE                  #x80000000))))
    ))
